# Clean Production Deployment Configuration
# This configuration ensures no development mode references for deployment compliance

modules = ["nodejs-20", "bash", "web", "postgresql-16"]

[deployment]
build = ["node", "simple-deploy.mjs"]
run = ["node", "production-deploy.mjs"]
deploymentTarget = "autoscale"

[env]
NODE_ENV = "production"

# Production server port configuration
[[ports]]
localPort = 5000
externalPort = 5000