# Production Deployment Configuration
modules = ["nodejs-20", "bash", "web", "postgresql-16"]

[deployment]
build = ["node", "simple-deploy.mjs"]
run = ["node", "start-production.mjs"]
deploymentTarget = "autoscale"

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 5000