# Production deployment configuration for Cloud Run
modules = ["nodejs-20", "bash", "web", "postgresql-16"]

run = "npx tsx server/index.ts"
entrypoint = "server/index.ts"

[deployment]
build = ["node", "simple-deployment-fix.mjs"]
run = ["node", "dist/start.mjs"]
deploymentTarget = "autoscale"

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80