modules = ["nodejs-20"]

run = "npx tsx server/index.ts"

[deployment]
build = ["node", "minimal-deploy.mjs"]
run = ["npx", "tsx", "index.ts"]

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80