modules = ["nodejs-20"]

run = "npx tsx server/index.ts"

[deployment]
build = ["node", "final-deploy.mjs"]
run = ["npx", "tsx", "server.ts"]

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80