modules = ["nodejs-20"]

run = "node start-pos.mjs"

[deployment]
build = ["node", "final-deploy.mjs"]
run = ["npx", "tsx", "server.ts"]

[env]
NODE_ENV = "production"

[[ports]]  
localPort = 5000
externalPort = 80

[[ports]]
localPort = 5000
externalPort = 8080