# Production-only configuration for deployment
modules = ["nodejs-20", "bash", "web", "postgresql-16"]

[deployment]
build = ["node", "simple-deploy.mjs"]
run = ["node", "production-start.mjs"]
deploymentTarget = "autoscale"

[env]
NODE_ENV = "production"