[run]
run = "npx tsx server/index.ts"

[deployment]
build = ["node", "simple-deploy.mjs"]
run = ["node", "start-production.mjs"]
ignoreBuildErrors = true

[env]
NODE_ENV = "production"

[nix]
channel = "stable-22_11"

[unitTest]
language = "nodejs"

[gitHubImport]
requiredFiles = [".replit", "replit.nix"]

[languages]

[languages.typescript]
pattern = "**/{*.ts,*.js,*.tsx,*.jsx,*.json}"

[languages.typescript.languageServer]
start = "typescript-language-server --stdio"