modules = ["nodejs-20"]

run = "npm run dev"

[deployment]
build = ["node", "final-deploy.mjs"]
run = ["npx", "tsx", "server.ts"]

[env]
NODE_ENV = "production"

[[ports]]  
localPort = 5000
externalPort = 80