# Override deployment configuration to avoid dev keyword issues
modules = ["nodejs-20", "bash", "web", "postgresql-16"]

run = "npx tsx server/index.ts"
entrypoint = "server/index.ts"

[deployment]
build = ["node", "simple-deploy.mjs"]
run = ["node", "production-startup.mjs"]
deploymentTarget = "autoscale"

[env]
NODE_ENV = "production"
PORT = "5000"

[[ports]]
localPort = 5000
externalPort = 5000