modules = ["nodejs-20"]

run = "node fixed-production-server.mjs"

[deployment]
build = ["node", "simple-deploy.mjs"]
run = ["node", "dist/server.mjs"]

[env]
NODE_ENV = "production"
PORT = "5000"

[[ports]]
localPort = 5000
externalPort = 80

[[ports]]  
localPort = 5173
externalPort = 8080